# Generated by Django 6.1.1 on 2026-09-26 15:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('minutes', 'Minutes'), ('dynamic', 'Minutes chosen on the spot'), ('access_change', 'Access change')], max_length=20, verbose_name='kind')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Share of the card's current parking fee that this discount pays.", max_digits=5, null=True, verbose_name='percentage')),
                ('minutes', models.PositiveIntegerField(blank=True, help_text='Free minutes added to the card.', null=True, verbose_name='minutes')),
                ('monthly_limit', models.PositiveIntegerField(default=0, help_text='Uses per calendar month for all users, 0 for no limit.', verbose_name='monthly limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('accesses', models.ManyToManyField(blank=True, help_text='The card must have one of these accesses (empty: any). Required for an access change.', related_name='+', to='core.access', verbose_name='accesses')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.parking', verbose_name='parking')),
                ('to_access', models.ForeignKey(blank=True, help_text='Access the card gets (access change).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.access', verbose_name='new access')),
                ('zones', models.ManyToManyField(blank=True, help_text='The card must be in one of these zones. Required, except for an access change (empty: any zone).', related_name='+', to='core.zone', verbose_name='zones')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
                'ordering': ['name'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField(verbose_name='card ID')),
                ('card_number', models.CharField(blank=True, max_length=32, verbose_name='card number')),
                ('plates', models.CharField(blank=True, max_length=100, verbose_name='plates')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('applied', 'applied')], default='pending', max_length=10, verbose_name='status')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='applied at')),
                ('applied_by_label', models.CharField(blank=True, max_length=150, verbose_name='applied by')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='discounts.discount', verbose_name='discount')),
            ],
            options={
                'verbose_name': 'discount usage',
                'verbose_name_plural': 'discount usages',
                'ordering': ['-applied_at'],
                'permissions': [('apply_discount', 'Can apply discounts')],
                'default_permissions': ('view', 'delete'),
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.PositiveIntegerField(default=0, help_text='Discounts this user may apply per calendar month, 0 for no limit.', verbose_name='monthly limit')),
                ('discounts', models.ManyToManyField(blank=True, related_name='users', to='discounts.discount', verbose_name='discounts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'discount user',
                'verbose_name_plural': 'discount users',
                'ordering': ['user__username'],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'percentage'), _negated=True), models.Q(('percentage__gt', 0), ('percentage__isnull', False), ('percentage__lte', 100)), _connector='OR'), name='discount_percentage_in_range', violation_error_message='A percentage discount needs a percentage above 0 and at most 100.'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'minutes'), _negated=True), models.Q(('minutes__gt', 0), ('minutes__isnull', False)), _connector='OR'), name='discount_minutes_set', violation_error_message='A minutes discount needs the number of minutes.'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'access_change'), _negated=True), ('to_access__isnull', False), _connector='OR'), name='discount_new_access_set', violation_error_message='An access change needs the new access.'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['discount', 'applied_at'], name='discounts_d_discoun_2bdce1_idx'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['applied_by', 'applied_at'], name='discounts_d_applied_f5571f_idx'),
        ),
        migrations.AddConstraint(
            model_name='discountusage',
            constraint=models.UniqueConstraint(fields=('card_id', 'discount'), name='discount_once_per_card'),
        ),
    ]
